on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x ${{ github.workspace }}/build.sh
          ${{ github.workspace }}/build.sh
